name: Dev - Terraform Plan

on:
  push:
    branches:
      - main
    paths:
      - 'environments/dev/**'
      - '.github/workflows/terraform-plan.yml'

  pull_request:
    paths:
      - 'environments/dev/**'
      - '.github/workflows/terraform-plan.yml'

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  TF_IN_AUTOMATION: true
  TF_ROOT: environments/dev

jobs:
  terraform-plan:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest

    environment: dev

    defaults:
      run:
        working-directory: ${{ env.TF_ROOT }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        working-directory: .
        run: |
          aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: |
          terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          terraform init -input=false

      - name: Terraform Validate
        run: |
          terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -input=false \
            -out=terraform.tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ github.run_id }}
          path: ${{ env.TF_ROOT }}/terraform.tfplan
          retention-days: 7