name: Test AWS OIDC

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1

jobs:
  run_job_with_aws:
    name: Test AWS Credentials
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Verify AWS Region
        run: |
          aws configure get region

      - name: Verify S3 Access
        run: |
          aws s3 ls